plugins: ./_plugins

permalink: /blog/:year/:month/:title

owner_link: http://kenhowardpdx.com/profile/

url: http://kenhowardpdx.com

domain: kenhowardpdx.com

title: A Blog About Website Design and Front-End Development

image: /images/logo.png

exclude: ["bower_components","node_modules","package.json","README.markdown","gulpfile.js","bower.json","Gem*"]
