plugins: ./_plugins

exclude: ['Rakefile','config.rb']

permalink: /blog/:year/:month/:title

owner_link: http://kenhowardpdx.com/profile/

url: http://kenhowardpdx.com

title: A Blog About Website Design and Front-End Development

image: /images/logo.png

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]